### ISSUE TITLE
stremids returns different response with and without level param

### ISSUE THREAD

**Issue by crotwell** [iris-edu/ringserver#10]
In v2018.047, [with level=4](http://rtserve.iris.washington.edu/streamids?level=4&match=^CO_BIRD_) gives:

```
CO_BIRD_00_HHE
CO_BIRD_00_HHN
CO_BIRD_00_HHZ
```

but same [url without level=4](http://rtserve.iris.washington.edu/streamids?match=^CO_BIRD_) gives:

```
CO_BIRD_00_HHE/MSEED
CO_BIRD_00_HHN/MSEED
CO_BIRD_00_HHZ/MSEED
```

I think the output should be the same regardless. Obviously the `/MSEED` should not be there for level that doesn't actually match a stream (ie !=4 in this example). I am not sure if it makes more sense to never have `/MSEED` in `/streamids` or if it should appear when the level matches the actual stream level. I lean towards having `/MSEED` only be in `/streams` and never in `/streamids`.

**Comment by chad-iris** [comment]
Thanks for picking through the small details.  I went with never including the types in the /streamids output.  Its is only IDs, if you want stream types you need to read the full /streams output.

Fixed in c2a60e7dcc530cf8caad040dfe316c0da284a189
