### ISSUE TITLE
streams with level parameter

### ISSUE THREAD

**Issue by crotwell** [iris-edu/ringserver#11]
Docs make it seem like level shoudl not be used with streams, but it changes output. level should either cause error or maybe be ignored with /streams

Ex:

http://rtserve.iris.washington.edu/streams?match=^AK_BCP.*
```
AK_BCP__BHE/MSEED  2018-02-20T17:13:54.208400Z  2018-02-20T18:29:04.088400Z
AK_BCP__BHN/MSEED  2018-02-20T17:13:58.868400Z  2018-02-20T18:28:22.988400Z
AK_BCP__BHZ/MSEED  2018-02-20T17:14:00.928400Z  2018-02-20T18:28:59.348400Z
...
```

http://rtserve.iris.washington.edu/streams?level=2&match=^AK_BCP.*
```
AK_BCP
```

http://rtserve.iris.washington.edu/streams?level=4&match=^AK_BCP.*
```
AK_BCP__BHE
AK_BCP__BHN
AK_BCP__BHZ
...
```

**Comment by chad-iris** [comment]
Fixed documentation in 79d65d5f4e39d51e7fa99ded04ce4b926c66bdd5.

The `level` parameter is not meant to be used with the /streams endpoint.  The functionality remains for backwards compatibility, but is undocumented.
