### ISSUE TITLE
use ringserver in release name

### ISSUE THREAD

**Issue by crotwell** [iris-edu/ringserver#14]
Current release is named 'v2018.078.tar.gz' but once the file is downloaded, and a few weeks (or minutes depending on memory) pass, you have no idea what it is. Much better to name it
`ringserver-2018.078.tar.gz`. Also nice if the untarred directory matches the filename. Currently the release untars to `ringserver-2018.078` which would match the above suggestion.

Seems like the standard is `packagename-<tag>.tar.gz` without a `v` in the tag.

**Comment by chad-iris** [comment]
Repeat of https://github.com/iris-edu/libmseed/issues/29
