### ISSUE TITLE
SeedLink Server

### ISSUE THREAD

**Issue by Mohammadkebria** [iris-edu/ringserver#22]
Hi 
we want to try implement seedlink server on Cortex M MCU. Would you please tell us that this approach could be implementable on this family of MCUs?  (Our MCU supports TCP/IP socket and free RTOS)

**Comment by chad-iris** [comment]
Hi @Mohammadkebria.  To be honest I have no idea.  I'm sure ringserver will run on a Raspberry PI (with an ARM Cortex-family of processor).  It's probably mostly dependent on the OS you are using.  The RPi has Raspbian which is unix/linux and provides the system libraries needed by ringserver.
