### ISSUE TITLE
ringserver configuration

### ISSUE THREAD

**Issue by ogalanis** [iris-edu/ringserver#28]
Hi,
  I was exploring my options for displaying waveforms in real time in a web page, and I came across this: http://crotwell.github.io/seisplotjs/tutorial/tutorial7.html by @Crotwell . It is not clear to me if it is possible to configure my ringserver the same way, i.e. to accept web socket connections using the DataLink protocol.
  I installed the ringserver and it works as expected, creating the ring buffer, and it can be configured to run as a SeedLink server and everything. However I still haven't managed to make something like the aforementioned link work with my ringserver, so I wonder if it is possible at all, or if I am missing something obvious in my .conf file or firewall settings or something.
  Any hints that may help me?

**Comment by crotwell** [comment]
Yes, that code was originally designed to work with ringserver. 

The ringserver conf option I use looks something like:
```
ListenPort 6382
WebRoot /data/scsn/www/ringserver-web
HTTPHeader "Access-Control-Allow-Origin: *"
```
but you can also use just HttpPort I believe. The HTTPHeader is important to allow connections from pages servered by another web server.

**Comment by ogalanis** [comment]
This did the trick. I didn't realize that the WebRoot option was necessary. Thank you!

**Comment by chad-iris** [comment]
Hmm, I wouldn't think the WebRoot is necessary as ringserver will answer HTTP requests (if configured to do so) regardless if a WebRoot has been set.  The HTTP `Access-Control-Allow-Origin` is definately important though.
