### ISSUE TITLE
Cryptography  between  miniseed2dmc and Ringserver

### ISSUE THREAD

**Issue by cajaraujo** [iris-edu/ringserver#36]
Hi guys,
is there some native way to use cryptography  between  miniseed2dmc and Ringserver? 
Thanks!

**Comment by chad-iris** [comment]
Hi @cajaraujo.
Currently there are no options for this.  There are probably ways to create an encrypted tunnel to use for transmission, for example with SSH, but you would need to control both ends of the connection to configure the tunnel.

In the future I anticipate adding support for TLS to ringserver and libdali, but there is no timeline for that.
