### ISSUE TITLE
Send_scnl wildcard doesn't send empty loc code channels

### ISSUE THREAD

**Issue by crotwell** [iris-edu/ringserver#7]
I have stations with both 00 and  blank loc codes. Doing this:
`Send_scnl * * CO *` only sends the 00 channels even though I have a * in the "l" spot.

Doing this
```
Send_scnl * * CO *
Send_scnl * * CO --
```
sends both types. Seems like the * wildcard should handle this case without needing a second Send_scnl line.

**Comment by chad-iris** [comment]
What is `Send_scnl`?  I do not recognize this as something related to `ringserver`, i.e. not something from the DataLink, SeedLink or HTTP protocols supported.

**Comment by crotwell** [comment]
ew2ringserver

I thought it was migrated to github as well, maybe not?

**Comment by chad-iris** [comment]
> I thought it was migrated to github as well, maybe not?

Nope.  It's in the EW repository, where all things EW seem to get get drawn in.
