### ISSUE TITLE
allow percent encoded chars in match 

### ISSUE THREAD

**Issue by crotwell** [iris-edu/ringserver#8]
Some libraries, like [python-requests](http://docs.python-requests.org/en/master/) percent encode certain characters. In particular some chars that are helpful to use in the regex for the match parameter to /streams like '^' are encoded as '%5E'. The result is that this URL returns data:

[http://rtserve.iris.washington.edu/streams?match=^CO_BIRD_](http://rtserve.iris.washington.edu/streams?match=^CO_BIRD_)
but even here, clicking the link in the github markdown seems to apply the percent encoding to the carrot, so even this one doesn't work.

but this one, that should be equivalent, does not:
[http://rtserve.iris.washington.edu/streams?match=%5ECO_BIRD_](http://rtserve.iris.washington.edu/streams?match=%5ECO_BIRD_)

For reference, Wikipedia on [percentEncoding](https://en.wikipedia.org/wiki/Percent-encoding).

**Comment by chad-iris** [comment]
Yup, should be easy enough to add a URL decoding step, ala:
http://www.rosettacode.org/wiki/URL_decoding#C

**Comment by chad-iris** [comment]
Thanks for the easy test case, that makes it so much easier!
